name = "freebuff2api"
main = "worker.js"
compatibility_date = "2024-01-01"

# Force Cloudflare to execute Worker in US (North America)
# This ensures Egress IP is ALWAYS from US datacenter to prevent 'ip_capped'
[placement]
mode = "smart"

[vars]
# API Key untuk autentikasi client
API_KEY = "freebuff-default-key"

# Mode Debug (true / false)
FREEBUFF_DEBUG = "false"

# Daftarkan token akun Codebuff/Freebuff di sini
FREEBUFF_TOKEN = ""

# Biarkan kosong jika direct worker di Cloudflare
RELAY_URL = ""
