name = "freebuff2api"
main = "worker.js"
compatibility_date = "2024-01-01"

# Targeted Placement to AWS US-East (US Region)
# Mengunci eksekusi worker 100% di US Datacenter (Anti ip_capped)
[placement]
mode = "targeted"
region = "aws:us-east-1"

[vars]
# API Key untuk autentikasi client
API_KEY = "freebuff-default-key"

# Mode Debug (true / false)
FREEBUFF_DEBUG = "false"

# Daftarkan token akun Codebuff/Freebuff di sini (bisa multi-token dipisah newline)
FREEBUFF_TOKEN = ""

# Biarkan kosong jika direct worker di Cloudflare
RELAY_URL = ""
